
#ifndef PG_BSK_PROJECT_CODES_HPP
#define PG_BSK_PROJECT_CODES_HPP

#include <rpc/client.h>

#include <crypto/Crypto.hpp>

enum MSG_TYPE {
// 	KEX_INIT = 0x01,
// 	KEX_RESPONSE = 0x02,
	MSG = 0x03,
	FILE_META = 0x04,
	FILE_BLOCK = 0x05,
	REQUEST_FILE_RESEND = 0x06
};

enum ERROR_CODE {
	SUCCESS = 0,
	FAILED = 0x11,
	FAILED_VALIDATION_MESSAGE = 0x12,
	FAILED_VALIDATION_KEX = 0x13,
	INVALID_FUNCTION_PER_TYPE = 0x14,
	FAILED_FILE_HASH_VALIDATION = -14
};

enum ENCRYPTION_MODE {
	CHACHA20 = 0x71,
	CHACHA20_POLY1305 = 0x72
};

MSGPACK_ADD_ENUM(MSG_TYPE);
MSGPACK_ADD_ENUM(ERROR_CODE);
MSGPACK_ADD_ENUM(ENCRYPTION_MODE);

#endif

